apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- http://localhost:3000/mayankino/argoapps-public.git

patches:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: bgd
    path: bgd-deployment.yaml