apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/mayankino/argoapps-demo.git
      revision: main
      directories:
      - path: core/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 15
          backoff:
            duration: 15s
            factor: 2
            maxDuration: 5m
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc